Time and mute options added Mute options is added because in Windows playing sounds cause the following error
events.js:72
        throw er; // Unhandled 'error' event
	              ^
		      Error: spawn ENOENT
		          at errnoException (child_process.js:988:11)
			      at Process.ChildProcess._handle.onexit
			      (child_process.js:779:34)